---
title: "preprocessing_tcga_exp"
author: "Fabian Strobel"
date: '2022-05-06'
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load original data (60,000x10,000 Matrix)
```{r}
## Does not work
#setwd('.')
#directory = "data/tcga_tumor_log2TPM.RDS"
#tcga_exp <- readRDS(directory)
```

## Checking for NAs and removing rows containing NAs
```{r}
rmv.rows = apply(tcga_exp,1,function(x){sum(is.na(x))}) # Go through each row and sum up all missing values
tcga_exp_cleaned = tcga_exp[- which(rmv.rows > 0),] # Removing any row with 1 or more missing values

dim(tcga_exp)
```

## Thresholding
```{r}
min(tcga_exp)
```

## Filtering
```{r}
#min.val.gene = apply(tcga_exp, 1, min)
#max.val.gene = apply(tcga_exp, 1, max)
#genes.remove = which(max.val.gene/min.val.gene <=5 | max.val.gene - min.val.gene <= 500)
#length(genes.remove) # --> 60498
```

```{r}
sd <- apply(tcga_exp, 1, sd)
var <- sd^2

hist(sd, main = "Histogramm for SD of each row"); abline(v = median(sd), col = "red")
hist(var, main = "Histogramm for variance of each row"); abline(v = median(var), col = "red")

quant = quantile(var, seq(0, 1, 0.1)) 
quant
hist(var, breaks = 30, main = "Variances for each row of tcga_exp \n and quantiles in 10 % steps"); abline(v = quant, col = "red", lty = 2)


median(sd)

## filtering to keep genes which have a variance greater than the 75% percentile
tcga_exp_cleaned = tcga_exp[tcga_exp > quantile(var, probs = 0.75),] 
```

