---
title: "02_additional_gene_sets"
author: "Fabian Strobel"
date: '2022-05-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load packages}
library(msigdbr)
```

```{r Load additional gene sets/pathways}
h_gene_sets = msigdbr(species = "Homo sapiens", category = "H")
head(h_gene_sets)

h_apical_junction <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_APICAL_JUNCTION",]
h_apical_surface <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_APICAL_SURFACE",]
h_dna_repair <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_DNA_REPAIR",]
h_spermatogenesis <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_SPERMATOGENESIS",]
h_g2m_checkpoint <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_G2M_CHECKPOINT",]
h_complement <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_COMPLEMENT",]
h_inflammatory_response <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_INFLAMMATORY_RESPONSE",]
h_epithelial_mesenchymal_transition <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION",]
h_angiogenesis <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_ANGIOGENESIS",]
h_reactive_oxygen_species <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY",]
h_apoptosis <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_APOPTOSIS",]
h_hypoxia <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_HYPOXIA",]
h_glycolysis <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_GLYCOLYSIS",]
h_fatty_acid_metabolism <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_FATTY_ACID_METABOLISM",]
h_oxidative_phosphorylation <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_OXIDATIVE_PHOSPHORYLATION",]
h_cholesterol_homeostasis <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_CHOLESTEROL_HOMEOSTASIS",]
h_bile_acid_metabolism <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_BILE_ACID_METABOLISM",]
h_heme_metabolism <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_HEME_METABOLISM",]
h_xenobiotic_metabolism <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_XENOBIOTIC_METABOLISM",]
h_peroxisome <- h_gene_sets[h_gene_sets$gs_name == "HALLMARK_PEROXISOME",]
```

```{r fusion as data.frame}
add_data_sets <- rbind(h_angiogenesis, h_apical_junction, h_apical_surface, h_apoptosis, h_bile_acid_metabolism, h_cholesterol_homeostasis, h_complement, h_dna_repair, h_epithelial_mesenchymal_transition, h_fatty_acid_metabolism, h_g2m_checkpoint, h_glycolysis, h_heme_metabolism, h_hypoxia, h_inflammatory_response, h_oxidative_phosphorylation, h_peroxisome, h_reactive_oxygen_species, h_spermatogenesis, h_xenobiotic_metabolism)
```

```{r extract gene sympols}
angiogenesis <- h_angiogenesis$gene_symbol
apical_junction <- h_apical_junction$gene_symbol
apical_surface <- h_apical_surface$gene_symbol
apoptosis <- h_apoptosis$gene_symbol
bile_acid_metabolism <- h_bile_acid_metabolism$gene_symbol
cholesterol_homeostasis <- h_cholesterol_homeostasis$gene_symbol
complement <- h_complement$gene_symbol
dna_repair <- h_dna_repair$gene_symbol
epithelial_mesenchymal_transition <- h_epithelial_mesenchymal_transition$gene_symbol
fatty_acid_metabolism <- h_fatty_acid_metabolism$gene_symbol
g2m_checkpoint <- h_g2m_checkpoint$gene_symbol
glycolysis <- h_glycolysis$gene_symbol
heme_metabolism <- h_heme_metabolism
hypoxia <- h_hypoxia$gene_symbol
inflammatory_response <- h_inflammatory_response$gene_symbol
oxidative_phosphorylation <- h_oxidative_phosphorylation$gene_symbol
peroxisome <- h_peroxisome$gene_symbol
reactive_oxygen_species <- h_reactive_oxygen_species$gene_symbol
spermatogenesis <- h_spermatogenesis$gene_symbol
xenobiotic_metabolism <- h_xenobiotic_metabolism$gene_symbol
```

```{r create list}
add_data_sets <- list("angiogenesis" = angiogenesis, 
                      "apical_junction" = apical_junction, 
                      "apical_surface" = apical_surface, 
                      "apoptosis" = apoptosis, 
                      "bile_acid_metabolism" = bile_acid_metabolism, 
                      "cholesterol_homeostasis" = cholesterol_homeostasis, 
                      "complement" = complement, 
                      "dna_repair" = dna_repair, 
                      "epithelial_mesenchymal_transition" = epithelial_mesenchymal_transition,
                      "fatty_acid_metabolism" = fatty_acid_metabolism,
                      "g2m_checkpoint" = g2m_checkpoint,
                      "glycolysis" = glycolysis,
                      "hypoxia" = hypoxia, 
                      "inflammatory_response" = inflammatory_response,
                      "oxidative_phosphorylation" = oxidative_phosphorylation,
                      "peroxisome" = peroxisome,
                      "reactive_oxygen_species" = reactive_oxygen_species,
                      "spermatogenesis" = spermatogenesis,
                      "xenobiotic_metabolism" = xenobiotic_metabolism)
```

```{r export}
saveRDS(add_data_sets, file = "add_data_sets")
```