---
title: "Challenge 2 fuction to automate plotting"
author: "Laura Lange"
date: '2022-06-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# p-value matrix (for pathways)

# for reproducible results set seed (runif )
set.seed(100)
df1 <- data.frame(matrix(runif(20*50, 1e-20, 1e-3), 20, 50),
                  row.names = paste("pathway", 1:20, sep = "_"))

set.seed(95)
df2 <- data.frame(matrix(runif(20*50, 1e-20, 1e-3), 20, 50),
                  row.names = paste("pathway", 1:20, sep = "_"))

df.p.value.list = list("LUAD" = df1, "BRCA" = df2)

# genset size information 

len.genesets <- sample(10:50, 20)
names(len.genesets) <- paste("pathway", 1:20, sep = "_")

head(len.genesets)
```

Crate function: get_top10pathways_from_pvalues()

function is useable for lapply(df_pvalues_list, function)
return a list("name1" = top10_df, "name2"= barplot, "name3" = dotplot)

```{r}
get_top10pathways_from_pvalues = function(df_p_values, length_genesets) {
  
  require(ggplot2)
  
  results <- list()
    
  df_p_values_log10 <- -log10(as.data.frame(df_p_values))
    
  mean_pathway <- as.data.frame(apply(df_p_values_log10, 1, mean))
  rownames(mean_pathway) <- rownames(df_p_values_log10)
  
  ordered_score <- mean_pathway[order(-mean_pathway[ ,1]), 1]
  top_10 <- data.frame(ordered_score[1:10])
  colnames(top_10) <- "mean_pathway"
  
  ordered_names <- order(-mean_pathway[ ,1])
  top_10_names <- ordered_names[1:10]
  top_10$pathway_names <- row.names(mean_pathway)[top_10_names]
  
  results[[1]] <- top_10
  
  results[[2]] <- ggplot(data = top_10, aes(x = mean_pathway, pathway_names))+
    geom_bar(stat = "identity")+
    labs(title = names(df_p_values))
  
  pathway_size <- order(-mean_pathway[ ,1])
  top_10_size <- pathway_size[1:10]
  top_10$pathway_size <- length_genesets[top_10_size]
  
  top_10$pathway_names <- as.factor(top_10$pathway_names)
  
  results[[3]] <- ggplot(data = top_10, aes(x = mean_pathway, y = pathway_names,
                                            fill = pathway_size))+
    geom_dotplot(position = "identity",
                 binwidth = 0.5,
                 binaxis = "y")+
    labs(title = names(df_p_values))
  
  print(results)
}
```

```{r}
get_top10pathways_from_pvalues(df.p.value.list[1], len.genesets)
                               
```

```{r}

lapply(df.p.value.list, get_top10pathways_from_pvalues, length_genesets = len.genesets)
# lapply(df.p.value.list, best_function, length_genesets = len.genesets)





lapply(df.p.value.list, get_top10pathways_from_pvalues, length_genesets = len.genesets)


dfs <- df.p.value.list

lapply(dfs, FUN= function(df){return(get_top10pathways_from_pvalues(df, len.genesets))})
```

