---
title: "Exploring data"
output: html_document
date: '2022-05-12'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("ggplot2")
#loading the data from the gitignore storage
#tcga_exp = readRDS("data/tcga_tumor_log2TPM.RDS")
tcga_exp_cleaned = readRDS("data/tcga_exp_cleaned.RDS")
tcga_annot = readRDS("data/tcga_tumor_annotation.RDS")
tcga_tumor_norm = readRDS("data/tcga_tumor_normal_datascience_proj_2022.RDS")
#genesets = readRDS("data/hallmarks_genesets.rds")
```
#test plot zum lernen und üben
```{r}
ggplot(tcga_annot, aes(age_at_initial_pathologic_diagnosis,color=cancer_type_abbreviation ))+ geom_histogram(fill="#AFFFFF")

```

#dataframe für Varianz un Mittelwert aller Gene (gerade nicht alle weil die daten zum rechnen zu groß sind)
```{r}
tcga_exp_var_mean <- data.frame(varianz=apply(tcga_exp_cleaned[1:1000,],1,var),mittelwert=apply(tcga_exp_cleaned[1:1000,],1,mean))

```

#plot aller Mittelwerte gegen die Varianz aller Gene
```{r}
ggplot(tcga_exp_var_mean, aes(mittelwert, varianz))+ geom_point(color="#808080",shape=1)
```
#ermitteln weniger gene mit hoher Varianz um Boxplotts zwischen ausgewählten Tumor Typen zu plotten
```{r}
tcga_exp_var_mean_orderd <- order(tcga_exp_var_mean[,"varianz"])
tgca_exp_tumortype <- data.frame(tcga_annot$cancer_type_abbreviation,t(tcga_exp_cleaned[tcga_exp_var_mean_orderd[1:5],]))
colnames(tgca_exp_tumortype) <- c("type","exp1","exp2","exp3","exp4","exp5")

tgca_exp_tumortype_selection <- data.frame(subset(tgca_exp_tumortype,type=="BRCA" |type=="KIRC" |type=="LUAD" |type=="PRAD" |type=="THCA"))

```

#vorerst nur 1. plot weil die for schleife irgendwie nicht funktioniert
```{r}
#for(i in 2:6){
ggplot(tgca_exp_tumortype_selection, aes(type, tgca_exp_tumortype_selection[,3],fill=type))+ geom_boxplot()
#}
```

