---
title: "Vulcano plot"
author: "Laura Lange"
date: '2022-05-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data
```{r}
tcga_tumor_norm = readRDS("data/tcga_tumor_normal_datascience_proj_2022.RDS")

# get list PRAD data
PRAD <- tcga_tumor_norm[[3]]

# get data frame PRAD normal
PRAD_normal <- PRAD[[1]]

# get data frame PRAD tumor 
PRAD_tumor <- PRAD[[2]]
```

Calculate mean or median for each gene 
```{r}
mean_normal <- apply(PRAD_normal, 1, mean)

mean_tumor <- apply(PRAD_tumor, 1, mean)
```

Calculate Fold Change log2[(T-N)/N]
T = tumor 
N = normal 
```{r}
FoldChange <- (mean_tumor - mean_normal) / mean_normal

log2FoldChange <- log2(FoldChange)
```


I do not get this!!!

Compare mean/median between normal and tumor (t-test)
```{r}
for(index in 1:nrow(PRAD_normal)){
    print(t.test(PRAD_normal[index, ], PRAD_tumor[index, ])$p.value)
    }
```

```{r}
PRAD_normal[1, ]

t.test(PRAD_normal[1, ], PRAD_tumor[1, ], alternative = "two.sided", paired = TRUE)$p.value
```
```{r}
p_values <- list()

for(index in 1:nrow(PRAD_normal)) {
  p_values <- c(p_values, t.test(PRAD_normal[index, ], PRAD_tumor[index, ])$p.value)
  }

```


Correct p-value via Bonferroni ("bonferroni") / Benjamini-Hichberg ("BH")
```{r}
corrected_p_value <- applay(p_values, 1, p.adjust(p_value, method = "bonferroni")
```

Make vulcano plot 

```{r}
log2_FoldChange <- rnorm(200)
p_value <- rnorm(200)
dat <- data.frame(log2_FoldChange, p_value)

# add a column of NAs
dat$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
dat$diffexpressed[dat$log2_FoldChange > 0.6 & dat$p_value < 0.05] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
dat$diffexpressed[dat$log2_FoldChange < -0.6 & dat$p_value < 0.05] <- "DOWN"

# Change point color
color <- c("blue", "red", "black")
names(color) <- c("DOWN", "UP", "NO")

ggplot(data = dat, mapping = aes(x=log2_FoldChange, y= -log10(p_value), col = diffexpressed))+
  geom_point() +
  theme_minimal() +
  scale_color_manual(values = color) +
  geom_vline(xintercept=c(-0.6, 0.6), col="red") +
  geom_hline(yintercept=-log10(0.05), col="red")
```



