---
title: "01_2_seurat_PCA_UMAP"
author: "Fabian Strobel"
date: '2022-06-09'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
setwd('..')
tcga_pancancer <- readRDS("data/tcga_pancancer.rds")
```

```{r}
pca <- Seurat::RunPCA(t(tcga_pancancer))
```

Each PC explains part of overall variance in tcga matrix, proportional to corresponding eigenvalue

Analysis of variance
```{r}
variance = (pca@stdev) ##Eigenvalues

barplot(log(variance), main = "log(variance) after pca for pan-cancer dataset", xlab = "PC_i", ylab = "log(variance)")
```

###
```{r}
# Get the standard deviations for each PC from the Seurat object
Seurat::Stdev(object = pca, reduction = "pca")
```
###

Scaling on 1 gives proportion of variance in percent
```{r}
prop.var = variance/pca@misc$total.variance

summary(prop.var)

barplot(prop.var[1:10], main = "Proportion of variance of the first 10 PCs", xlab = "PCs", ylab = "Proprtion of variance")
```


```{r}
new.coordinates = pca@feature.loadings

par(mfrow = c(2,3))

plot(new.coordinates[,1],new.coordinates[,2],pch=19,
     xlab='PC1',ylab='PC2')

plot(new.coordinates[,1],new.coordinates[,3],pch=19,
     xlab='PC1',ylab='PC3')

plot(new.coordinates[,1],new.coordinates[,4],pch=19,
     xlab='PC1',ylab='PC4')

plot(new.coordinates[,2],new.coordinates[,3],pch=19,
     xlab='PC2',ylab='PC3')

plot(new.coordinates[,2],new.coordinates[,4],pch=19,
     xlab='PC2',ylab='PC4')

plot(new.coordinates[,3],new.coordinates[,4],pch=19,
     xlab='PC3',ylab='PC4')

mtext("PC biplots for pancancer analysis",
      side = 3,
      line = - 2,
      outer = TRUE)

par(mfrow = c(1,1))
```


***
#UMAP

```{r}
umap_pan <- uwot::umap(pca@feature.loadings)
```

```{r}
library(ggplot2)
library(randomcoloR)

tcga_tumor_annotation <- readRDS("data/tcga_tumor_annotation.rds")

cancer_type <- tcga_tumor_annotation$cancer_type_abbreviation

umap <- cbind(as.data.frame(umap_pan), cancer_type)


# Basic scatter plot
set.seed(123)

pal <- c(randomColor(count = length(unique(cancer_type))))

ggplot(umap, aes(x = V1, y = V2, color = cancer_type)) + 
  geom_point() +
  scale_color_manual(values = pal) +
  xlab("V1???") +
  ylab("V2???") +
  ggtitle("UMAP pancancer")
```

