---
title: "01_seurat_PCA_UMAP"
author: "Fabian Strobel"
date: '2022-06-09'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
setwd('..')
tcga_pancancer <- readRDS("data/tcga_pancancer.rds")
tcga_tumor_annotation <- readRDS("data/tcga_tumor_annotation.rds")
library(ggplot2)
library(gridExtra)
library(randomcoloR)
set.seed(123)
```

```{r}
pca <- Seurat::RunPCA(as.matrix(tcga_pancancer))
```

Each PC explains part of overall variance in tcga matrix, proportional to corresponding eigenvalue

Analysis of variance
```{r}
variance = (pca@stdev) ##Eigenvalues

barplot(log(variance), main = "log(variance) after pca for pan-cancer dataset", xlab = "PC_i", ylab = "log(variance)")
```

###
```{r}
# Get the standard deviations for each PC from the Seurat object
Seurat::Stdev(object = pca, reduction = "pca")
```
###

Scaling on 1 gives proportion of variance in percent
```{r}
prop.var = variance/pca@misc$total.variance

summary(prop.var)

barplot(prop.var[1:10], main = "Proportion of variance of the first 10 PCs", xlab = "PCs", ylab = "Proprtion of variance")
```


```{r}
new.coordinates = as.data.frame(pca@cell.embeddings)

PCbiplot <- function(coords){
  require(ggplot2)
  require(gridExtra)
  
  a <- ggplot(data = coords, mapping = aes(x = PC_1, y = PC_2)) +
  geom_point()
  
  b <- ggplot(data = coords, mapping = aes(x = PC_1, y = PC_3)) +
  geom_point()
  
  c <- ggplot(data = coords, mapping = aes(x = PC_1, y = PC_4)) +
  geom_point()
  
  d <- ggplot(data = coords, mapping = aes(x = PC_2, y = PC_3)) +
  geom_point()
          
  e <- ggplot(data = coords, mapping = aes(x = PC_2, y = PC_4)) +
  geom_point()
  
  f <- ggplot(data = coords, mapping = aes(x = PC_3, y = PC_4)) +
  geom_point()
  
  grid.arrange(a,b,c,d,e,f, ncol = 3, top = "PC biplots for pancancer analysis")
}

PCbiplot(new.coordinates)
```


***
#UMAP

```{r}
set.seed(123); umap_pan <- uwot::umap(pca@cell.embeddings)
```

```{r}
cancer_type <- tcga_tumor_annotation$cancer_type_abbreviation

umap <- cbind(as.data.frame(umap_pan), cancer_type)

# Basic scatter plot
n <- length(unique(cancer_type))

set.seed(123); pal <- c(distinctColorPalette(k = n))

ggplot(umap, aes(x = V1, y = V2, color = cancer_type)) + 
  geom_point(alpha = .5) +
  scale_color_manual(values = pal) +
  xlab("UMAP1") +
  ylab("UMAP2") +
  ggtitle("UMAP pancancer")
```