---
title: "Challenge 1 Paul"
author: "Fabian Strobel"
date: '2022-06-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
tcga_pancancer <- readRDS("data/tcga_pancancer.rds")
pathways <- readRDS("data/total_pathways_ensID.rds")
tcga_anno <- readRDS("data/tcga_tumor_annotation.RDS")
```


```{r}
#createn einer liste mit allen patienten in dfs sortiert nach krebs
cancers = list();cancers = vector('list',length(table(tcga_anno$cancer_type_abbreviation)))
names(cancers) = names(table(tcga_anno$cancer_type_abbreviation))
for (i in 1:length(cancers)){
  cancers[[i]] = tcga_pancancer[,tcga_anno$cancer_type_abbreviation == names(cancers)[i]]
}
```


```{r}
library(parallel)


#enrichment funktion
enrichment = function(expressiondata, genesets = genesets_ids){
  ESmatrix = sapply(genesets, FUN = function(x){
    print(names(x))
    ins = na.omit(which(rownames(expressiondata) %in% x == TRUE))#indices der gene im aktuellen set
    outs = -ins#indices der gene nicht im aktuellen set
    #gibt einen vektor der f체r jeden patienten den pval f체r das aktuelle gene enth채lt
    res = NULL
    for (i in 1:ncol(expressiondata)){#testet f체r jeden patienten
      res[i] = wilcox.test(expressiondata[ins,i],expressiondata[outs,i],'two.sided')$p.value
    }
    return(res)
  })
  row.names(ESmatrix) = colnames(expressiondata); return(ESmatrix)
}

## IOS
pvalueslist_metabol = mclapply(cancers, FUN = function(x){enrichment(x,pathways)}, mc.cores = 2)

## Windows
cl <- makeCluster(2) # Number of cores
## Complete the rest of the arguments as needed
pvalueslist_metabol = parLapply(cl, cancers, fun = function(x){
  enrichment(x,pathways)})
```
