---
title: "Pathway activity matrix"
author: "Fabian Strobel"
date: '2022-06-20'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
setwd('..')
tcga_pvalues <- readRDS("data/tcga_pvalues.rds")
```

I dunno why but each entry of the pvalue matrix is of class "list"
```{r}
class(tcga_pvalues[1,1])
```
This needs to be changed to numeric if we want to use it in mathematical functions
```{r}
pathways <- rownames(tcga_pvalues)
pvalues <- apply(tcga_pvalues, 2, as.numeric)
rownames(pvalues) = pathways
class(pvalues[1,1])
```

Also, data.frames are cooler than matrices
```{r}
pvalues <- as.data.frame(pvalues)
```

Lets perform a -log10 transformation
```{r}
pvalues_log10 <- -log10(pvalues)
```

***

```{r}
library(pheatmap)
setwd('..')
tcga_annot <- readRDS("data/tcga_tumor_annotation.rds")
```

Annotations
```{r}
cancer_annot <- as.data.frame(tcga_annot$cancer_type_abbreviation)
rownames(cancer_annot) = colnames(pvalues_log10)
colnames(cancer_annot)[1] = "cancer type"
head(cancer_annot)
```


```{r}
pheatmap(pvalues_log10,
         show_colnames = F,
         cluster_rows = F,
         annotation_col = cancer_annot,
         fontsize = 6)

pheatmap(pvalues_log10,
         show_colnames = F,
         cluster_cols = F,
         annotation_col = cancer_annot,
         fontsize = 6)

pheatmap(pvalues_log10,
         show_colnames = F,
         annotation_col = cancer_annot,
         fontsize = 6)
```

