---
title: "Dimension reduction small pvalue matrix"
author: "Fabian Strobel"
date: '2022-06-20'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
setwd('..')
tcga_pvalue_topvar <- readRDS("data/tcga_pvalue_topvar.rds")
tcga_tumor_annotation <- readRDS("data/tcga_tumor_annotation.rds")
library(ggplot2)
library(gridExtra)
library(randomcoloR)
library(dplyr)
set.seed(123)
```

```{r}
pvalue_pw_activity <- -log10(tcga_pvalue_topvar)
```


## Dimension reduction

### PCA
```{r}
pca <- Seurat::RunPCA(as.matrix(pvalue_pw_activity), npcs = 2)
```

```{r}
new.coordinates = as.data.frame(pca@cell.embeddings)

PCbiplot <- function(coords){
  require(ggplot2)
  require(gridExtra)
  
  a <- ggplot(data = coords, mapping = aes(x = PC_1, y = PC_2)) +
  geom_point()
  
  b <- ggplot(data = coords, mapping = aes(x = PC_1, y = PC_3)) +
  geom_point()
  
  c <- ggplot(data = coords, mapping = aes(x = PC_1, y = PC_4)) +
  geom_point()
  
  d <- ggplot(data = coords, mapping = aes(x = PC_2, y = PC_3)) +
  geom_point()
          
  e <- ggplot(data = coords, mapping = aes(x = PC_2, y = PC_4)) +
  geom_point()
  
  f <- ggplot(data = coords, mapping = aes(x = PC_3, y = PC_4)) +
  geom_point()
  
  grid.arrange(a,b,c,d,e,f, ncol = 3, top = "PC biplots for log10 p value matrix")
}

PCbiplot(new.coordinates)
```

### UMAP

```{r}
#set.seed(123); umap_pan <- uwot::umap(pca@cell.embeddings, n_neighbors = 100)

set.seed(123); umap_pan_cosine <- uwot::umap(pca@cell.embeddings, metric = "cosine", n_neighbors = 15)
```

```{r}
cancer_type <- tcga_tumor_annotation$cancer_type_abbreviation

umap <- cbind(as.data.frame(umap_pan_cosine), cancer_type)

# Basic scatter plot
n <- length(unique(cancer_type))

set.seed(123); pal <- c(distinctColorPalette(k = n))

ggplot(umap, aes(x = V1, y = V2, color = cancer_type)) + 
  geom_point(alpha = .5) +
  scale_color_manual(values = pal) +
  xlab("UMAP1") +
  ylab("UMAP2") +
  ggtitle("UMAP GSVA cosine n_neighbors = 15")
```

***

Visualize pw activity

```{r}
## Compute variance
variance <- as.data.frame(apply(tcga_pvalue_topvar, 1, var))
colnames(variance) = "variance"

## sort descending
var_sorted <- arrange(variance, desc(variance))

## take 9 pws mit highes variance
topVar <- rownames(var_sorted)[1:9]

## get GSVA scores
pw_act <- t(as.data.frame(tcga_pvalue_topvar[topVar,]))

## Combine UMAP and Pathway activity
umap_act <- cbind(as.data.frame(umap_pan_cosine), pw_act)
```

```{r}
for(i in 3:ncol(umap_act)) { 
  nam <- paste("A", i, sep = "")
  
  plots_i <- ggplot(umap_act, aes(x = V1, y = V2)) + 
  geom_point(alpha = 1, aes_string(color = noquote(names(umap_act)[i]))) +
  scale_color_gradient(low = "darkblue", high = "yellow") +
  xlab("UMAP1") +
  ylab("UMAP2") +
  ggtitle(paste(names(umap_act[i]))) +
  theme(plot.title = element_text(size = 10)) +
  labs(color = "Pathway\nactivity")
  
    assign(nam, plots_i)
}

grid.arrange(A3, A4, A5, A6, A7, A8, A9, A10, A11,
             ncol = 3, 
             top = paste("UMAP after GSVA with pathway activities"))
```


