---
title: "Split pathway activity matrix due to cancer type"
author: "Laura Lange"
date: '2022-06-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Load data

```{r}
setwd('..')
tcga_pw_activity <- readRDS("data/tcga_pw_activity")
tcga_tumor_annotation <- readRDS("data/tcga_tumor_annotation")

# When **** is not working 
tcga_pw_activity <- readRDS("~/GitHub/2022-topic-02-team-04/data/tcga_pw_activity.rds")
tcga_tumor_annotation <- readRDS("~/GitHub/2022-topic-02-team-04/data/tcga_tumor_annotation.RDS")


# use pathway activity function in mathematical functions

pathways <- rownames(tcga_pw_activity)
pvalues <- apply(tcga_pw_activity, 2, as.numeric)
rownames(pvalues) = pathways

pvalues <- as.data.frame(pvalues)
```

2. Liste mit Pathway activity matrix per cancer Types

```{r}
#createn einer liste mit allen patienten in dfs sortiert nach krebs

pathway_activ_cancer = list();

pathway_activ_cancer = vector('list',length(table(tcga_tumor_annotation$cancer_type_abbreviation)))
names(pathway_activ_cancer) = names(table(tcga_tumor_annotation$cancer_type_abbreviation))

for (i in 1:length(pathway_activ_cancer)){
  pathway_activ_cancer[[i]] = pvalues[,tcga_tumor_annotation$cancer_type_abbreviation == names(pathway_activ_cancer)[i]]
}
```

3. Get Vector with gene set length 

```{r}
# load data 
total_pathways_ensID <- readRDS("data/total_pathways_ensID")

total_pathways_ensID <- readRDS("~/GitHub/2022-topic-02-team-04/data/total_pathways_ensID.rds")

# length(total_pathways_ensID[[1]])

# get size of gene sets 
size_pathway <- vector()
for (i in 1:length(total_pathways_ensID)){
  size_pathway[i] <- length(total_pathways_ensID[[i]])
}
names(size_pathway) <- names(total_pathways_ensID)
```

4. apply funciton form challange 2

```{r}
get_top10pathways_from_pvalues = function(df_p_values, length_genesets) {
  
  require(ggplot2)
  
  results <- list()
    
  df_p_values_log10 <- -log10(as.data.frame(df_p_values))
    
  mean_pathway <- apply(as.data.frame(pathway_activ_cancer[1]), 1, mean)
  rownames(mean_pathway) <- rownames(df_p_values_log10)
  
  ordered_score <- mean_pathway[order(-mean_pathway[ ,1]), 1]
  top_10 <- data.frame(ordered_score[1:10])
  colnames(top_10) <- "mean_pathway"
  
  ordered_names <- order(-mean_pathway[ ,1])
  top_10_names <- ordered_names[1:10]
  top_10$pathway_names <- row.names(mean_pathway)[top_10_names]
  
  results[[1]] <- top_10
  names(results)[[1]] <- "data_frame"
  
  results[[2]] <- ggplot(data = top_10, aes(x = mean_pathway, y = reorder(pathway_names, mean_pathway)))+
    geom_bar(stat = "identity")+
    labs(title = names(df_p_values),
         x = "mean p-value pathway",
         y = "pathway name")
  names(results)[[2]] <- "bar_plot"
  
  pathway_size <- order(-mean_pathway[ ,1])
  top_10_size <- pathway_size[1:10]
  top_10$pathway_size <- length_genesets[top_10_size]
  
  results[[3]] <- ggplot(data = top_10, aes(x = mean_pathway, y = reorder(pathway_names,
                                                                          mean_pathway)))+
    geom_point(aes(size = pathway_size))+
    labs(title = names(df_p_values),
         x = "mean p-value pathway",
         y = "pathway name")
  names(results)[[3]] <- "dot_plot"
  
  return(results)
}
```

```{r}
# apply function for p-value matrix = weird 
# top_10_pathways <- lapply(pathway_activ_cancer, get_top10pathways_from_pvalues, length_genesets = size_pathway)
# rather use for loop :)

pathway_activ_cancer[1]

apply(pathway_activ_cancer[[1]], 1, mean)

apply(as.data.frame(pathway_activ_cancer[1]), 1, mean)



get_top10pathways_from_pvalues(pathway_activ_cancer[1], size_pathway)

top_10_pathways <- list()
  
for (i in 1:length(pathway_activ_cancer)){
  top_10_pathways[[i]] <- get_top10pathways_from_pvalues(pathway_activ_cancer[i], size_pathway)
  names(top_10_pathways)[[i]] <- names(pathway_activ_cancer[i])
}
print(top_10_pathways["PRAD"])
```

