---
title: "GSVA pathway activity matrix"
author: "Fabian Strobel"
date: '2022-06-20'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
setwd('..')
pw_activity_full_TCGA_df <- readRDS("data/pw_activity_full_TCGA_df.rds")
tcga_annot <- readRDS("data/tcga_tumor_annotation.rds")

library(pheatmap)
```

Annotations
```{r}
## cancertype
cancer_annot <- as.data.frame(sort(tcga_annot$cancer_type_abbreviation))
colnames(cancer_annot)[1] = "Cancer type"
rownames(cancer_annot) = colnames(pw_activity_full_TCGA_df)

## pathways
g <- rep("Given Sets", 46)
h <- rep("MSigDB Hallmarks", 50)
k <- rep("KEGG", 186-3)
o <- rep("Oncogenic Sigantures", 189)
t <- rep("Ontology", 84)

pw_annot <- as.data.frame(c(g, h, k, o, t))

colnames(pw_annot) <- "Gene sets"
rownames(pw_annot) <- rownames(pw_activity_full_TCGA_df)
```

Heatmap
```{r}
pdf(file = "11_1_GSVA_heatmap2.pdf", height = 2*11.69, width = 2*11.69)

pheatmap(pw_activity_full_TCGA_df,
         show_colnames = F,
         show_rownames = F,
         cluster_cols = T,
         cluster_rows = F,
         treeheight_row = 0,
         treeheight_col = 0,
         cutree_cols = 2,
         anotation_col = cancer_annot)

dev.off()
```


Mean variance plot
```{r}
library(ggplot2)

m <- apply(pw_activity_full_TCGA_df, 1, mean)
v <- apply(pw_activity_full_TCGA_df, 1, var)

mv <- data.frame(mean = m, variance = v)

ggplot(data = mv, aes(x = mean, y = variance)) + 
  geom_point()
```

```{r}
topVar <- pw_activity_full_TCGA_df[which(v > 0.125),]

pheatmap(topVar,
         show_colnames = F,
         show_rownames = T,
         cluster_cols = T,
         cluster_rows = T,
         fontsize = 10,
         main = "Heatmap GSVA, 40 Pathways with highest variance",
         cutree_rows = 3,
         annotation_col = cancer_annot)
```



***

Mean over cancer types

```{r}
#createn einer liste mit allen patienten in dfs sortiert nach krebs
cancers = list();cancers = vector('list',length(table(tcga_tumor_annotation$cancer_type_abbreviation)))
names(cancers) = names(table(tcga_tumor_annotation$cancer_type_abbreviation))
for (i in 1:length(cancers)){
  cancers[[i]] = pw_activity_full_TCGA_df[,tcga_tumor_annotation$cancer_type_abbreviation == names(cancers)[i]]
}
```


```{r}
mean_score <- lapply(cancers, FUN = function(cancer_type){
  apply(cancer_type, 1, mean)
})

mean_pw_activity <- do.call(cbind.data.frame, mean_score)
```

```{r}
pheatmap(mean_pw_activity,
         show_colnames = T,
         show_rownames = F,
         cluster_cols = T,
         cluster_rows = T,
         annotation_row = pw_annot,
         fontsize = 10,
         main = "Heatmap after GSVA mean by cancer type",
         cutree_cols = 3)
```

```{r}
library(ggplot2)

m <- apply(mean_pw_activity, 1, mean)
v <- apply(mean_pw_activity, 1, var)

mv <- data.frame(mean = m, variance = v)

ggplot(data = mv, aes(x = mean, y = variance)) + 
  geom_point()

topVar <- mean_pw_activity[which(v > 0.0704),]

pheatmap(topVar,
         show_colnames = T,
         show_rownames = T,
         cluster_cols = T,
         cluster_rows = T,
         fontsize = 10,
         cutree_cols = 3,
         cutree_rows = 3,
         main = "Heatmap GSVA, 40 Pathways with highest variance, mean cancer type")
```

***

Pathway Correlation
```{r}
cor_pw <- cor(t(pw_activity_full_TCGA_df))
diag(cor_pw) = NA

## pathway annotation
g <- rep("Given Sets", 46)
h <- rep("MSigDB Hallmarks", 50)
k <- rep("KEGG", 186-3)
o <- rep("Oncogenic Sigantures", 189)
t <- rep("Ontology", 84)

pw_annot <- as.data.frame(c(g, h, k, o, t))

colnames(pw_annot) <- "Gene sets"
rownames(pw_annot) <- rownames(pw_activity_full_TCGA_df)

pheatmap(cor_pw,
         show_colnames = F,
         show_rownames = F,
         treeheight_row = 0,
         cluster_cols = T,
         cluster_rows = T,
         main = "Correlation Heatmap of pathways after GSVA",
         cutree_cols = 2,
         cutree_rows = 2,
         annotation_col = pw_annot)

```

Cancers correlation
```{r}
cor_cancer_types <- cor(pw_activity_full_TCGA_df)
diag(cor_cancer_types) = NA

pdf(file = "11_9_GSVA_heatmap_correlation_cancers.pdf", height = 2*11.69, width = 2*11.69)

pheatmap(cor_cancer_types,
         show_colnames = T,
         show_rownames = T,
         cluster_cols = T,
         cluster_rows = T,
         cutree_rows = 3,
         cutree_cols = 3,
         annotation_col = cancer_annot,
         main = "Correlation Heatmap of means over cancer types after GSVA")

dev.off()
```

Cancers correlation
```{r}
cor_cancer_types <- cor(mean_pw_activity)
diag(cor_cancer_types) = NA

pheatmap(cor_cancer_types,
         show_colnames = T,
         show_rownames = T,
         cluster_cols = T,
         cluster_rows = T,
         cutree_rows = 3,
         cutree_cols = 3,
         main = "Correlation Heatmap of means over cancer types after GSVA")
```