---
title: "GSVA pathway activity matrix"
author: "Fabian Strobel"
date: '2022-06-20'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
setwd('..')
tcga_pw_activity <- readRDS("data/tcga_pw_activity")
tcga_annot <- readRDS("data/tcga_tumor_annotation.rds")

library(pheatmap)
```

Annotations
```{r}
## cancertype
cancer_annot <- t(as.data.frame(sort(tcga_annot$cancer_type_abbreviation)))
rownames(cancer_annot)[1] = "Cancer type"
colnames(cancer_annot) = colnames(tcga_pw_activity)

colnames(tcga_pw_activity) %in% cancer_annot

## pathways
g <- rep("Given Sets", 46)
h <- rep("MSigDB Hallmarks", 50)
k <- rep("KEGG", 186-3)
o <- rep("Oncogenic Sigantures", 189)
t <- rep("Ontology", 84)

pw_annot <- as.data.frame(c(g, h, k, o, t))

colnames(pw_annot) <- "Gene sets"
rownames(pw_annot) <- rownames(tcga_pw_activity)
```

Heatmap
```{r}
pheatmap(tcga_pw_activity,
         show_colnames = F,
         show_rownames = F,
         cluster_cols = F,
         cluster_rows = F,
         annotation_col = cancer_annot,
         annotation_row = pw_annot)

pheatmap(tcga_pw_activity,
         show_colnames = F,
         show_rownames = F,
         cluster_cols = T,
         cluster_rows = T,
         annotation_col = cancer_annot,
         annotation_row = pw_annot)

pheatmap(tcga_pw_activity,
         show_colnames = F,
         show_rownames = F,
         cluster_cols = F,
         cluster_rows = F,
         annotation_col = cancer_annot,
         annotation_row = pw_annot)
```

Mean variance plot
```{r}
library(ggplot2)

m <- apply(tcga_pw_activity, 1, mean)
v <- apply(tcga_pw_activity, 1, var)

mv <- data.frame(mean = m, variance = v)

ggplot(data = mv, aes(x = mean, y = variance)) + 
  geom_point()
```

```{r}
topVar <- tcga_pw_activity[which(v > 0.125),]

pheatmap(topVar,
         show_colnames = F,
         show_rownames = T,
         cluster_cols = T,
         cluster_rows = T,
         fontsize = 10,
         main = "Heatmap GSVA, 40 Pathways with highest variance",
         cutree_rows = 3)
```



***

Mean over cancer types
```{r}
tcga_pw_activity_list <- readRDS("data/tcga_pw_activity")
```

```{r}
mean_score <- lapply(tcga_pw_activity_list, FUN = function(cancer_type){
  apply(cancer_type, 1, mean)
})

mean_pw_activity <- do.call(cbind.data.frame, mean_score)
```

```{r}
pheatmap(mean_pw_activity,
         show_colnames = T,
         show_rownames = F,
         cluster_cols = T,
         cluster_rows = T,
         annotation_row = pw_annot,
         fontsize = 6,
         main = "Heatmap after GSVA mean by cancer type",
         cutree_cols = 4)
```

```{r}
library(ggplot2)

m <- apply(mean_pw_activity, 1, mean)
v <- apply(mean_pw_activity, 1, var)

mv <- data.frame(mean = m, variance = v)

ggplot(data = mv, aes(x = mean, y = variance)) + 
  geom_point()

topVar <- mean_pw_activity[which(v > 0.000155),]

pheatmap(topVar,
         show_colnames = T,
         show_rownames = T,
         cluster_cols = T,
         cluster_rows = T,
         fontsize = 10,
         main = "Heatmap GSVA, 40 Pathways with highest variance, mean cancer type")
```

