---
title: "Regression"
author: "Fabian Strobel"
date: '2022-07-08'
output: html_document
---

```{r}
#pw_activity_full_TCGA_df <- readRDS("data/pw_activity_full_TCGA_df.rds")

library(pheatmap)
library(dplyr)
```

```{r}
## Transpose to get correlation of pw activity
pw_activity <- t(pw_activity_full_TCGA_df)

## Correlation
cor_mat <- cor(pw_activity)
diag(cor_mat) = NA
```

```{r}
pheatmap(cor_mat,
         show_rownames = F,
         show_colnames = F)
```

```{r}
## Compute variance
variance <- as.data.frame(apply(pw_activity, 2, var))
colnames(variance) = "variance"

## sort descending
var_sorted <- arrange(variance, desc(variance))

## take 9 pws mit highes variance
topVar <- rownames(var_sorted)[1:9]

## take these pws
topVar_pw <- as.data.frame(pw_activity[,topVar])

##
topVar_cor <- cor(topVar_pw); diag(topVar_cor) = NA
pheatmap(topVar_cor,
         show_colnames = F)
```


```{r}
lr = lm(KEGG_NUCLEOTIDE_EXCISION_REPAIR ~ HALLMARK_G2M_CHECKPOINT, data=topVar_pw)
summary(lr)

hist(lr$residuals)
qqnorm(lr$residuals); qqline(lr$residuals)
cor(topVar_pw$HALLMARK_G2M_CHECKPOINT, lr$residuals)
plot(topVar_pw$HALLMARK_G2M_CHECKPOINT, lr$residuals)
```
```{r}
plot(topVar_pw$KEGG_NUCLEOTIDE_EXCISION_REPAIR,lr$fitted.values,pch=20,col='blue', xlab='Real values',ylab='Predicted values');abline(0,1,col='red')
```

```{r}
l1 <- lm(topVar_pw$KEGG_NUCLEOTIDE_EXCISION_REPAIR ~ ., topVar_pw)
summary(l1)
```

```{r}
plot(topVar_pw$KEGG_NUCLEOTIDE_EXCISION_REPAIR, l1$fitted.values,pch=20,col='blue', xlab='Real values',ylab='Predicted values');abline(0,1,col='red')
```

root mean squared error (RMSE)
```{r}
n = nrow(pw_activity)
rmse = sqrt(1/n*sum(l1$residuals^2))
rmse
```

***

Divide in training and testing set (70/30)
```{r}
## take 70 % random patients to form the training set
set.seed(123); i.train = sample(1:nrow(topVar_pw), round(nrow(topVar_pw)*0.7,0))
##
dat.train = topVar_pw[i.train,]
dat.test = topVar_pw[-i.train,]
```

```{r}
l.train = lm(dat.train$KEGG_NUCLEOTIDE_EXCISION_REPAIR ~ ., dat.train)
summary(l.train)
```

```{r}
n = nrow(dat.train)
rmse.train = sqrt(1/n*sum(l.train$residuals^2))
rmse.train
```

```{r}
pred = predict(l.train,newdata = dat.test)
```

```{r}
n = nrow(dat.test)
residuals = dat.test$KEGG_NUCLEOTIDE_EXCISION_REPAIR - pred
rmse.test = sqrt(1/n * sum(residuals^2))
rmse.test
```

