---
title: "Vulcano plot new"
author: "Laura Lange"
date: '2022-05-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data

```{r}
tcga_tumor_norm <- readRDS("~/GitHub/2022-topic-02-team-04/data/PRAD_TvsN.rds")
```
Load data
```{r}
# Fuse data frame PRAD normal with PRAD tumor
PRAD_tumor_normal <- cbind(tcga_tumor_norm[["tumor"]], tcga_tumor_norm[["normal"]])

class(PRAD_tumor_normal)
```

Calculate mean for each gene 

```{r}
mean_normal <- apply(PRAD_tumor_normal[ ,1:52], 1, mean)

mean_tumor <- apply(PRAD_tumor_normal[ ,53:104], 1, mean)
```

Calculate Fold Change 

$$
log_2[(T)/N]
$$

T = tumor 
N = normal 

```{r}
e_mean_tumor <- 2^mean_tumor
e_mean_normal <- 2^mean_normal
FoldChange <- e_mean_tumor / e_mean_normal

# Scale Fold Change 
log2_FoldChange <- log2(FoldChange)
```

Calculate significane of the fold change (paired wilcox-test)

```{r}
# calculate p-value with apply function 

p_value <- apply(PRAD_tumor_normal, 1, function(x) wilcox.test(x[1:52], 
                                                         x[53:104], 
                                                         paired = TRUE,
                                                         exact = FALSE)$p.value)

# we will continue working with this p-values

# Scale p-values 
log10_p_value <- log10(p_value)
```


```{r}
# calculate p-value with for loop; stored in data frame

p_value_2 <- data.frame(NA_col = rep(NA, 8159))



for(index in 1:nrow(PRAD_tumor_normal)) {
  p_value_2[index, ] <- wilcox.test(as.matrix(PRAD_tumor_normal[index,1:52]), 
                                    as.matrix(PRAD_tumor_normal[index,53:104]),
                                    paired = TRUE,
                                    exact = FALSE)$p.value
  }

colnames(p_value_2) <- c("p-value")
```


```{r}
# calculate p-value with for loop; stored in matrix

p_value_3 <- matrix(nrow = 8159, ncol = 116)

for(index in 1:nrow(PRAD_tumor_normal)) {
  p_value_3[index, ] <- wilcox.test(PRAD_tumor_normal[index,1:52], 
                                    PRAD_tumor_normal[index,53:104],
                                    paired = TRUE,
                                    exact = FALSE)$p.value
  }
```

Plot not corrected p-values 

```{r}
# not correced p-values 
hist(p_value, breaks = 20)
```

correct p-values and plot them again 

```{r}
# correct p-value via Bonferroni ("bonferroni") / Benjamini-Hichberg ("BH")
corrected_p_value <- p.adjust(p_value, method = "bonferroni")

# plot correced p-values 
hist(corrected_p_value, breaks = 20)

# Scale corrected p-values 
log10_corrected_p_value <- log10(corrected_p_value)

```
Create vulcano plot with not correced p-values 

```{r}
dat <- data.frame(log2_FoldChange, log10_p_value)

# add a column of NAs
dat$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
dat$diffexpressed[dat$log2_FoldChange > log2(2) & dat$log10_p_value < log10(0.05)] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
dat$diffexpressed[dat$log2_FoldChange < log2(0.5) & dat$log10_p_value < log10(0.05)] <- "DOWN"

# Change point appearance 
color <- c("blue", "red", "black")
names(color) <- c("DOWN", "UP", "NO")

library(ggplot2)

ggplot(data = dat, mapping = aes(x=log2_FoldChange, 
                                 y= -log10_p_value, 
                                 col = diffexpressed))+
  geom_point()+
  scale_color_manual(values = color)+
  geom_vline(xintercept=c(log2(0.5), log2(2)), linetype="dashed", col="black")+
  geom_hline(yintercept=-log10(0.05), linetype="dashed", col="black")+
  scale_x_continuous(breaks = c(seq(-7, 7, 2)),
                     limits = c(-7, 7))+
  labs(title = "Vulcano plot")
```

Create vulcano plot with corrected p-values 

```{r}
dat_2 <- data.frame(log2_FoldChange, log10_corrected_p_value)

# add a column of NAs
dat_2$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
dat_2$diffexpressed[dat_2$log2_FoldChange > log2(2) & dat_2$log10_corrected_p_value < log10(0.05)] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
dat_2$diffexpressed[dat_2$log2_FoldChange < log2(0.5) & dat_2$log10_corrected_p_value < log10(0.05)] <- "DOWN"

# Change point appearance 
color <- c("blue", "red", "black")
names(color) <- c("DOWN", "UP", "NO")

library(ggplot2)

ggplot(data = dat_2, mapping = aes(x= log2_FoldChange, 
                                   y= -log10_corrected_p_value, 
                                   col= diffexpressed))+
  geom_point()+
  scale_color_manual(values = color)+
  geom_vline(xintercept=c(log2(0.5), log2(2)), linetype="dashed", col="darkgreen")+
  geom_hline(yintercept=-log10(0.05), linetype="dashed", col="darkgreen")+
  scale_x_continuous(breaks = c(seq(-7, 7, 2)),
                     limits = c(-7, 7))+
  labs(title = "Vulcano plot")
```

Create vulcano plot with genes of one pathway 

```{r}
dat_2 <- data.frame(log2_FoldChange, log10_corrected_p_value)

# add a column of NAs
dat_2$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
dat_2$diffexpressed[dat_2$log2_FoldChange > log2(2) & dat_2$log10_corrected_p_value < log10(0.05)] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
dat_2$diffexpressed[dat_2$log2_FoldChange < log2(0.5) & dat_2$log10_corrected_p_value < log10(0.05)] <- "DOWN"

# character of all genes 
all_genes <- rownames(PRAD_tumor_normal)
class(all_genes)
# character of all genes in pathway
total_pathways_ensID <- readRDS("~/GitHub/2022-topic-02-team-04/data/total_pathways_ensID.rds")

pathway_genes <- total_pathways_ensID$spermatogenesis
class(pathway_genes)
# add column: TRUE if gene is in pathway + FALSE if it is not
dat_2$pathway_genes <- !is.na(match(all_genes, pathway_genes))


# Change appearance 
color <- c("blue", "green", "black", "red")
names(color) <- c("DOWN", "UP", "NO", "TRUE")

library(ggplot2)

ggplot(data = dat_2, mapping = aes(x = log2_FoldChange, 
                                   y = -log10_corrected_p_value))+
  geom_point(aes(col = diffexpressed))+
  geom_point(aes(alpha = pathway_genes,
                 size = pathway_genes,
                 shape = pathway_genes,
                 col = pathway_genes))+
  scale_color_manual(values = color)+
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.1))+
  scale_size_manual(values = c("TRUE" = 4, "FALSE" = 0.1))+
  scale_shape_manual(values = c("TRUE" = 18, "FALSE" = 20))+
  geom_vline(xintercept = c(log2(0.5), log2(2)), linetype = "dashed", col = "darkgreen")+
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", col = "darkgreen")+
  scale_x_continuous(breaks = c(seq(-7, 7, 2)),
                     limits = c(-7, 7))+
  labs(title = "Vulcano plot")
```

