---
title: "Rank p-values for GSEA (PRAD analysis)"
author: "Laura Lange"
date: '2022-06-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data

```{r}
setwd('..')
tcga_tumor_norm <- readRDS("data/PRAD_TvsN.rds")

# Fuse data frame PRAD normal with PRAD tumor
PRAD_tumor_normal <- cbind(tcga_tumor_norm[["tumor"]], tcga_tumor_norm[["normal"]])
```

Create list of ranked genes 

Calculate mean for each gene 
```{r}
mean_normal <- apply(PRAD_tumor_normal[ ,1:52], 1, mean)

mean_tumor <- apply(PRAD_tumor_normal[ ,53:104], 1, mean)
```

Calculate Fold Change
```{r}
e_mean_tumor <- 2^mean_tumor
e_mean_normal <- 2^mean_normal
FoldChange <- e_mean_tumor / e_mean_normal

# Scale Fold Change 
log2_FoldChange <- log2(FoldChange)
```

Calculate significane of the fold change (paired wilcox-test)
```{r}
# calculate p-value with apply function 

p_value <- apply(PRAD_tumor_normal, 1, function(x) wilcox.test(x[1:52], 
                                                         x[53:104], 
                                                         paired = TRUE,
                                                         exact = FALSE)$p.value)

# Scale p-values 
neg_log10_p_value <- -log10(p_value)
```

Create data frame with gene number, Fold Change and p-value
```{r}
# get names of all genes 
gene_number <- rownames(PRAD_tumor_normal)

dat_for_ranking <- data.frame(gene_number, neg_log10_p_value, FoldChange)
```

Rank genes using fold change 
```{r}
# Search for same Fold Change
duplicated_FC <- duplicated(FoldChange)

length(duplicated_FC[duplicated_FC == TRUE])

# Rank Fold Change; for genes with same Fold Change: randomly decided which gets higher number 
dat_for_ranking$rank_FC <- rank(FoldChange, ties.method = "random")

# Check if there are no duplicates any more 
duplicated_ranks_FC <- duplicated(dat_for_ranking$rank_FC)

length(duplicated_ranks_FC[duplicated_ranks_FC == TRUE])

# Arragne genes in new order 
library(dplyr)
ranked_genes_FC <- dat_for_ranking %>% arrange(desc(dat_for_ranking$rank_FC))
```

Rank genes using p-values 
```{r}
# Calculate Ranking Score
ranking_score_p_value <- neg_log10_p_value * sign(log2_FoldChange)

# Search for same Ranking Score 
duplicated_p <- duplicated(ranking_score_p_value)

length(duplicated_p[duplicated_p == TRUE])

# Rank Fold Change; for genes with same Ranking Score: randomly decided which gets higher number 
dat_for_ranking$rank_p <- rank(ranking_score_p_value, ties.method = "random")

# Check if there are no duplicates any more 
duplicated_ranks_p <- duplicated(dat_for_ranking$rank)

length(duplicated_ranks_p[duplicated_ranks_p == TRUE])

# Arragne genes in new order 
library(dplyr)
ranked_genes_p <- dat_for_ranking %>% arrange(desc(dat_for_ranking$rank_p))
```

