---
title: "Volcano_plot_pathways"
author: "Laura Lange"
date: '2022-07-04'
output: html_document
---

Volcano plot

Load data

```{r}
setwd('..')
tcga_tumor_norm <- readRDS("data/PRAD_tumor_normal_pw_activity.rds")

PRAD_tumor_normal_pw_activity <- readRDS("~/GitHub/2022-topic-02-team-04/data/PRAD_tumor_normal_pw_activity.rds")
```

Calculate mean for each gene 

```{r}
mean_tumor <- apply(PRAD_tumor_normal_pw_activity[ ,1:52], 1, mean)

mean_normal <- apply(PRAD_tumor_normal_pw_activity[ ,53:104], 1, mean)
```

Calculate Fold Change 

$$
log_2[(T)/N]
$$

T = tumor 
N = normal 

```{r}
e_mean_tumor <- 2^mean_tumor
e_mean_normal <- 2^mean_normal
FoldChange <- e_mean_tumor / e_mean_normal
# Scale Fold Change 
log2_FoldChange <- log2(FoldChange)

# durch mathematische Umformung kommt man auch auf:
FoldChange_Diff <- (mean_tumor - mean_normal)


head(log2_FoldChange)
head(FoldChange_Diff)
```

Calculate significane of the fold change (paired wilcox-test)

```{r}
# calculate p-value with apply function 

p_value <- apply(PRAD_tumor_normal_pw_activity, 1, function(x) wilcox.test(x[1:52], 
                                                                           x[53:104],
                                                                           paired = TRUE,
                                                                           exact = FALSE)$p.value)

# we will continue working with this p-values

# Scale p-values 
log10_p_value <- log10(p_value)
```

Plot not corrected p-values 

```{r}
# not correced p-values 
hist(p_value, breaks = 20)
```

correct p-values and plot them again 

```{r}
# correct p-value via Bonferroni ("bonferroni") / Benjamini-Hichberg ("BH")
corrected_p_value <- p.adjust(p_value, method = "bonferroni")

# plot correced p-values 
hist(corrected_p_value, breaks = 20)

# Scale corrected p-values 
log10_corrected_p_value <- log10(corrected_p_value)

```

Create volcano plot with not correced p-values 

```{r}
dat <- data.frame(log2_FoldChange, log10_p_value)

# add a column of NAs
dat$diffexpressed <- "NO"
# if log2Foldchange > 0.4 and pvalue < 0.05, set as "UP" 
dat$diffexpressed[dat$log2_FoldChange > 0.4 & dat$log10_p_value < log10(0.05)] <- "UP"
# if log2Foldchange < -0.4 and pvalue < 0.05, set as "DOWN"
dat$diffexpressed[dat$log2_FoldChange < -0.4 & dat$log10_p_value < log10(0.05)] <- "DOWN"

# Change point appearance 
color <- c("blue", "red", "black")
names(color) <- c("DOWN", "UP", "NO")

library(ggplot2)

ggplot(data = dat, mapping = aes(x=log2_FoldChange, 
                                 y= -log10_p_value, 
                                 col = diffexpressed))+
  geom_point()+
  scale_color_manual(values = color)+
  geom_vline(xintercept=c(-0.4, 0.4), linetype="dashed", col="black")+
  geom_hline(yintercept=-log10(0.05), linetype="dashed", col="black")+
  scale_x_continuous(breaks = c(seq(-1, 1, 0.2)),
                     limits = c(-1, 1))+
  labs(title = "Volcano plot")
```

Create volcano plot with corrected p-values 

```{r}
dat_2 <- data.frame(log2_FoldChange, log10_corrected_p_value)

# add a column of NAs
dat_2$diffexpressed <- "NO"
# if log2Foldchange > 0.4 and pvalue < 0.05, set as "UP" 
dat_2$diffexpressed[dat_2$log2_FoldChange > 0.4 & dat_2$log10_corrected_p_value < log10(0.05)] <- "UP"
# if log2Foldchange < -0.4 and pvalue < 0.05, set as "DOWN"
dat_2$diffexpressed[dat_2$log2_FoldChange < -0.4 & dat_2$log10_corrected_p_value < log10(0.05)] <- "DOWN"

# Change point appearance 
color <- c("blue", "red", "black")
names(color) <- c("DOWN", "UP", "NO")

library(ggplot2)

ggplot(data = dat_2, mapping = aes(x= log2_FoldChange, 
                                   y= -log10_corrected_p_value, 
                                   col= diffexpressed))+
  geom_point()+
  scale_color_manual(values = color)+
  geom_vline(xintercept=c(-0.4, 0.4), linetype="dashed", col="darkgreen")+
  geom_hline(yintercept=-log10(0.05), linetype="dashed", col="darkgreen")+
  scale_x_continuous(breaks = c(seq(-1, 1, 0.2)),
                     limits = c(-1, 1))+
  labs(title = "Volcano plot")
```

