---
title: "Vulcano plot"
author: "Laura Lange"
date: '2022-05-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data
```{r}
tcga_tumor_norm = readRDS("data/tcga_tumor_normal_datascience_proj_2022.RDS")

# get list PRAD data
PRAD <- tcga_tumor_norm[[3]]
```

Clean data 

```{r}
# Fuse data frame PRAD normal with PRAD tumor
PRAD_normal_tumor <- cbind(PRAD[[1]], PRAD[[2]])

# Check for NA
PRAD_na <- apply(PRAD_normal_tumor, 1, function(x) any(is.na(x)))
rownames(PRAD_na)

# Get rid of genes that are not expressed (Variance < 1)
SD <- apply(PRAD_normal_tumor, 1, sd)
Vari <- SD^2

PRAD_Var <- which(Vari < 1)
PRAD_Cleaned <- PRAD_normal_tumor[Vari > 1, ]

# control
Cleaned <- apply(PRAD_Cleaned, 1, var)
min(Cleaned)

dim(PRAD_Cleaned)

# Seperate date set again 
PRAD_normal <- (PRAD_Cleaned[ ,1:58])

PRAD_tumor <- (PRAD_Cleaned[ ,59:116])

```

Calculate mean or median for each gene 
```{r}
mean_normal <- apply(PRAD_normal, 1, mean)

mean_tumor <- apply(PRAD_tumor, 1, mean)
```

Calculate Fold Change 
$$
log_2[(T)/N]
$$
T = tumor 
N = normal 
```{r}
e_mean_tumor <- 2^mean_tumor
e_mean_normal <- 2^mean_normal
FoldChange <- (e_mean_tumor) / e_mean_normal

log2FoldChange <- log2(FoldChange)
```
Compare mean/median between normal and tumor (t-test)

```{r}
PRAD_normal[1,1]

class(as.matrix (PRAD_normal[1, ]))


wilcox.test(as.numeric(PRAD_normal[1, ]), as.numeric(PRAD_tumor[1, ]), paired = TRUE, alternative = "two.sided")
```
```{r}
p_values <- list()

for(index in 1:nrow(PRAD_normal)) {
  p_values <- c(p_values, wilcox.test(
    as.matrix(PRAD_normal[index, ]),
    as.matrix(PRAD_tumor[index, ]), 
    paired = TRUE, alternative = "two.sided")$p.value)
  }

hist(as.numeric(p_values), breaks = 20)
```


Correct p-value via Bonferroni ("bonferroni") / Benjamini-Hichberg ("BH")
```{r}
corrected_p_value <- p.adjust(p_values, method = "bonferroni")

hist(as.numeric(corrected_p_value), breaks = 20)

```
Make vulcano plot 

```{r}
log2_FoldChange <- log2FoldChange
p_value <- corrected_p_value
dat <- data.frame(log2_FoldChange, p_value)

# add a column of NAs
dat$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
dat$diffexpressed[dat$log2_FoldChange > 0.6 & dat$p_value < 0.05] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
dat$diffexpressed[dat$log2_FoldChange < -0.6 & dat$p_value < 0.05] <- "DOWN"

# Change point color
color <- c("blue", "red", "black")
names(color) <- c("DOWN", "UP", "NO")

library(ggplot2)

ggplot(data = dat, mapping = aes(x=log2_FoldChange, y= -log10(p_value), col = diffexpressed))+
  geom_point() +
  theme_minimal() +
  scale_color_manual(values = color) +
  geom_vline(xintercept=c(-0.6, 0.6), col="red") +
  geom_hline(yintercept=-log10(0.05), col="red") +
  labs(title = "Vulcano plot")
```
