---
title: "Vulcano plot different approach"
author: "Laura Lange"
date: '2022-05-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data

```{r}
# get list PRAD data
PRAD <- tcga_tumor_norm[[3]]

# Fuse data frame PRAD normal with PRAD tumor
PRAD_normal_tumor <- cbind(PRAD[[1]], PRAD[[2]])
```

Clean data 

```{r}
# Check for NA
PRAD_na <- apply(PRAD_normal_tumor, 1, function(x) any(is.na(x)))
rownames(PRAD_na)

# Get rid of genes that are not expressed (Variance < 1)
SD <- apply(PRAD_normal_tumor, 1, sd)
Vari <- SD^2

PRAD_Var <- which(Vari < 1)
PRAD_cleaned <- PRAD_normal_tumor[Vari > 1, ]

# control
Cleaned <- apply(PRAD_cleaned, 1, var)
min(Cleaned)

dim(PRAD_cleaned)

```

```{r}
class(PRAD_cleaned)

# transform data frame into matrix 
PRAD_matrix <- as.matrix(PRAD_cleaned)

```


```{r}
# funktioniert mit apply nicht (warum?)
# p_value <- apply(PRAD_matrix, 1, function(x) t.test(x[ ,1:58], x[ ,59:116], paired = TRUE)$p.value)

p_value <- data.frame(NA_col = rep(NA, 8851))

for(index in 1:nrow(PRAD_matrix)) {
  p_value[index, ] <- wilcox.test(PRAD_matrix[index,1:58], 
                                  PRAD_matrix[index,59:116],
                                  paired = TRUE,
                                  exact = FALSE)$p.value
  }
```

```{r}
hist(as.matrix(p_value), breaks = 20)
```

